In [2]:
!pip install hazm

  Using cached hazm-0.10.0-py3-none-any.whl.metadata (11 kB)
  Using cached flashtext-2.7.tar.gz (14 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached numpy-1.24.3.tar.gz (10.9 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'


  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Ali\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Ali\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Ali\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "C:\Users\Ali\AppData\Local\Programs\Python\Python312\Lib\site-packa

In [ ]:
import numpy as np


print(np.__version__)

1.26.4


In [1]:
import pandas as pd
import hazm

In [ ]:
df = pd.read_csv("../data/news_data.csv")
df.head()

content        label  label_id
0  به گزارش حوزه ادبیات گروه فرهنگی باشگاه خبرنگا...  فرهنگی هنری         5
1  به گزارش خبرنگار دانشگاه باشگاه خبرنگاران، نما...        سیاسی         3
2  به گزارش حوزه تحولات منطقه گروه سیاسی باشگاه خ...        سیاسی         3
3  به گزارش خبرنگار حوزه رادیو تلویزیون گروه فرهن...  فرهنگی هنری         5
4  واکنش‌ها نسبت به لغو حضور مدافع سابق تیم ملی ف...        سیاسی         3

In [ ]:
print("تعداد سطرها و ستون‌ها:", df.shape)

# نمایش نام ستون‌ها
print("نام ستون‌ها:", df.columns.tolist())

# نمایش چند نمونه تصادفی از داده‌ها
df.sample(5)

تعداد سطرها و ستون‌ها: (5000, 3)
نام ستون‌ها: ['content', 'label', 'label_id']


content        label  label_id
3995  به گزارش خبرنگار گروه علمی و دانشگاهی خبرگزاری...  علمی فناوری         4
345   به گزارش سرویس علمی، ‌ پزشکی باشگاه خبرنگاران؛...        پزشکی         7
4960  وی تاکید کرد: مراقبت پرواز در کشور نیاز به همف...      اقتصادی         1
4553  به گزارش باشگاه خبرنگاران؛ محمد یوسف سپهری راد...  فرهنگی هنری         5
2262  به گزارش سرویس بین‌ الملل باشگاه خبرنگاران، مح...    بین الملل         2

In [7]:
data = df.copy()
data.head()

content        label  label_id
0  به گزارش حوزه ادبیات گروه فرهنگی باشگاه خبرنگا...  فرهنگی هنری         5
1  به گزارش خبرنگار دانشگاه باشگاه خبرنگاران، نما...        سیاسی         3
2  به گزارش حوزه تحولات منطقه گروه سیاسی باشگاه خ...        سیاسی         3
3  به گزارش خبرنگار حوزه رادیو تلویزیون گروه فرهن...  فرهنگی هنری         5
4  واکنش‌ها نسبت به لغو حضور مدافع سابق تیم ملی ف...        سیاسی         3

In [ ]:
import re
from hazm import Normalizer
from hazm import WordTokenizer
from hazm import Lemmatizer
from hazm import stopwords_list


lemmatizer = Lemmatizer()
normalizer = Normalizer()
tokenizer = WordTokenizer()
stop_words = set(stopwords_list())


def persian_text_preprocessing(text):
    # نرمال‌سازی متن
    text = normalizer.normalize(text)

    # حذف علائم نگارشی و اعداد
    text = re.sub(r"[^\w\s]", " ", text)  # حذف علائم نگارشی
    text = re.sub(r"\d+", " ", text)  # حذف اعداد
    text = re.sub(r"\s+", " ", text)  # حذف فاصله‌های اضافی

    # توکن‌سازی
    tokens = tokenizer.tokenize(text)

    # حذف کلمات توقف
    tokens = [word for word in tokens if word not in stop_words]

    # ریشه‌یابی
    lemmas = [lemmatizer.lemmatize(word) for word in tokens]

    # بازترکیب توکن‌ها به متن نهایی
    return " ".join(lemmas)

In [9]:
data["content"] = data["content"].apply(persian_text_preprocessing)

In [10]:
data["content"].sample(5).values

array(['گزار ش گروه اجتماعی باشگاه خبرنگار بهمن اسکندری خط مترو کیلومتر ایستگاه فاز دست احداث اظهارکرد خط مترو عمیق ترین خط مترو تهران خطوط تقاطع طوری خط ازبزرگراه هجرت ورزشگاه جهان پهلوان تختی جنوب شرق تهران آغاز بزرگراه اشرفی اصفهانی شمال غرب تهران ادامه اسکندری خط ایستگاه زمینی عمق سطح زمین تقریبا خطوط مترو گذر مجری پروژه خط مترو تصریح کیلومتر فاز پروژه ایستگاه فاصل میدان محمدیه گیشا دست اجراس حفاری تونل مسیر صد صد اتمام رسید#رس ایستگاه درصد پیشرفت فیزیکی شاهد اسکندری اشاره فاز ایستگاه بهره قرار گرفت#گیر برنامه صورت تامین اعتبارات خط شهریور آماده بهره مجری خط مترو تهران اشاره دستگاه مکانیزه حفار تی ام حاضر فاز خط حفاری دستگاه تی ام TBM خط مترو حفاری جنوب شمال تهران محدوده خیابان نواب بریانک خط میدان کتابی کیلومتر پیشروی طوری کیلومتر مسیر حفاری اسکندری دستگاه تی ام شرقی غربی خط حاضر روزانه حفاری انجام دستگاه حفار میدان قیام قرار طوری کیلومتر مسیر حفاری کیلومتر حفاری ادامه اگرچه طراحی اولیه مسیر حفاری دلیل سست خاک بافت فرسوده مسیر میدان قیام شرق ادامه خط خط محدوده کوی نصر تقاطع چمران 

In [ ]:
data["tag"] = data["label"] + " " + data["content"]

In [ ]:
data["tag"].sample(5).values

array(['فرهنگی هنری گزارش حوزه رادیو تلویزیون باشگاه خبرنگار گذر ازرنج ها سریال مخاطب دی ماه شبکه سیما آنتن توانست#توان زمان کوتاهی مخاطب جلب فریدون حسن پور کارگردان مجموعه ساخت سریال یاد رفته توانست#توان دل مردم سریال تاریخی تحولات سیاسی اجتماعی سال های زندگی واقعی تصویر کشت#کش پا خانه مردم گذاشته سرگذشت دختری رعیت روایت دلیل ظلم ستم های ارباب رعیتی جریانات پیچ خمی زندگی روایت استقبال گفت#گوی علی لدنی مجید پتک بازیگرنقش سهراب داشت#دار ادامه گذراند#گذران تجربه یاد رفته پذیرفتن کار مصمم علی لدنی سریال گذر رنج ها همکاری پروژه سوال پرسید#پرس لدنی همکاری پروژه ازکجا شکل ازهمکاری ام درسریال موفق یاد رفته پیشنهاد ساخت بعدی حسن پور افتخار پذیرفت#پذیر حسن پور سال هاست زمینه سریال فعالیت کمتر شناخت#شناس حس نوستالژی ارتباط مخاطب اشراف فرهنگ بومی شناخت#شناس درستی تصویر کشت#کش سریال یاد رفته سریال مخاطب بیشترین امتیاز اختصاص گذر رنج ها شکل زمانی طرح مدیر شبکه ارائه کرد#کن مخالفت پذیرفت#پذیر مراحل ساخت آغاز تولید کار زمان آغاز تولید کار سال آغاز لوکیشن های دلخواه فضای قصه همخوانی راهی شمال شد#شو خا

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# تعریف بردارساز TF-IDF با بیشینه ۵۰۰۰ ویژگی
tfidf = TfidfVectorizer(max_features=5000)

# اعمال بردارسازی روی ستون tag
tfidf_matrix = tfidf.fit_transform(data["tag"])

In [ ]:
print("شکل ماتریس TF-IDF:", tfidf_matrix.shape)

شکل ماتریس TF-IDF: (5000, 5000)


In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

# محاسبه شباهت کسینوسی بین بردارهای TF-IDF
similarity_matrix = cosine_similarity(tfidf_matrix)

In [ ]:
print("شکل ماتریس شباهت:", similarity_matrix.shape)

# مشاهده بخشی از ماتریس (مثلاً 5x5 اول)
import numpy as np

np.set_printoptions(precision=3, suppress=True)
print(similarity_matrix[:5, :5])

شکل ماتریس شباهت: (5000, 5000)
[[1.    0.119 0.014 0.035 0.048]
 [0.119 1.    0.066 0.029 0.089]
 [0.014 0.066 1.    0.007 0.04 ]
 [0.035 0.029 0.007 1.    0.101]
 [0.048 0.089 0.04  0.101 1.   ]]


In [ ]:
def find_similar_news(news_index, similarity_matrix, data, top_n=5):
    if news_index < 0 or news_index >= len(data):
        print("شماره خبر معتبر نیست.")
        return []

    similarities = similarity_matrix[news_index]
    similar_indices = similarities.argsort()[::-1]
    similar_indices = [i for i in similar_indices if i != news_index]
    top_similar = similar_indices[:top_n]

    return top_similar

In [ ]:
print(df["content"][2])

به گزارش حوزه تحولات منطقه گروه سیاسی باشگاه خبرنگاران جوان؛ نیروهای ارتش سوریه همزمان با تامین امنیت هزاران غیر نظامی محاصره شده توسط گروه‌های تروریستی جهت خروج از غوطه شرقی، شهرک حموریه را نیز آزاد کردند. نیروهای ارتش و هلال احمر سوریه امنیت هزاران شهروند محاصره شده در غوطه شرقی را برای خروج از آن و انتقال به مکان امن تامین کردند. همچنین طبق اعلام برخی منابع، ارتش سوریه پس از ۱۵ روز درگیری بر ۷۰ درصد مساحت تحت تسلط تروریست‌ها در غوطه شرقی مسلط شده است. روند پیشروی نیروهای ارتش سوریه در غوطه شرقی در استان ریف دمشق همچنان ادامه دارد. گروه‌های تروریستی مستقر در غوطه شرقی از یک ماه قبل تاکنون بیشتر مناطق مسکونی دمشق را با شلیک موشک و خمپاره هدف قرار داده‌اند که در اثر این اقدام تروریستی، تعداد زیادی از شهروندان سوری کشته و یا زخمی شده‌اند. این حملات همچنین به واردشدن خسارت هایی به اموال شهروندان سوری و زیرساخت‌های عمومی پایتخت سوریه منجر شده است.


In [ ]:
suggestion_result = find_similar_news(2, similarity_matrix, data)

print("\n✅ اخبار پیشنهادی مشابه با خبر شماره 2:\n")
for idx in suggestion_result:
    print(f"🔸 خبر مشابه #{idx}:\n{df.iloc[idx]['content'][:300]}...")
    print("—" * 80)


✅ اخبار پیشنهادی مشابه با خبر شماره 2:

🔸 خبر مشابه #3659:
به گزارش گروه بین الملل باشگاه خبرنگاران جوان به نقل از شبکه تلویزیونی العالم؛ نیروهای ارتش سوریه در شرق حلب به پیشروی‌های قابل ملاحظه‌ای دست یافتند. بر این اساس، ارتش سوریه و نیروهای هم پیمان در ادامه عملیات نظامی خود در محورهای باب النیرب و الصالحین پس از شکست دادن تروریست‌ها به پیشروی‌های قابل مل...
————————————————————————————————————————————————————————————————————————————————
🔸 خبر مشابه #2838:
به گزارش سرویس بین‌ الملل باشگاه خبرنگاران به نقل از شبکه تلویزیونی سوریه؛ ارتش این کشور توانست پس از هدف قرار دادن همه مراکز و کانونهای تجمع تروریستها در این منطقه آنرا پاکسازی کند و امنیت را به آن بازگرداند. گزارشگر شبکه تلویزیونی سوریه که با همراهی ارتش این کشور گزارشی در این خصوص تهیه کرده است؛ ...
————————————————————————————————————————————————————————————————————————————————
🔸 خبر مشابه #1360:
در جریان این حملات، علاوه بر انهدام ادوات تروریست‌ها، شماری از آن‌ها نیز به هلاکت رسیدند و برخی دیگر زخمی شدند. از سوی دیگر، منابع س

In [20]:
# پیدا کردن ۵ خبر مشابه با خبر شماره ۴۶
similar_indices = find_similar_news(46, similarity_matrix, data, top_n=5)

In [ ]:
# ساخت دیتافریم خروجی شامل label و index
submission = pd.DataFrame(
    {"label": df.loc[similar_indices, "label"].values, "index": similar_indices}
)

In [22]:
submission

label  index
0  علمی فناوری   1688
1  علمی فناوری   4844
2  علمی فناوری   2578
3  علمی فناوری   2048
4  علمی فناوری   3142